### ISSUE TITLE
tox automation issues

### ISSUE THREAD

**Issue by mahmoud** [pyninsula/website#4]
Few issues when doing the recent update

1) The automation doesn't create the CNAME file, meaning DNS breaks.
2) Commenting/uncommenting things in tox is a bizarre API and at the very least worth having a README.
3) When I do uncomment the `push-gh` line in the tox.ini, I get:

```
$ tox
site installed: blinker==1.4,docutils==0.14,feedgenerator==1.9,Jinja2==2.10,MarkupSafe==1.0,pelican==3.7.1,Pygments==2.2.0,python-dateutil==2.6.1,pytz==2018.3,six==1.11.0,Unidecode==1.0.22
site runtests: PYTHONHASHSEED='1314602693'
site runtests: commands[0] | pelican -t theme/tuxlite_tbs -o /home/mahmoud/projects/pyninsula_website/build/tox/site/tmp/output content
Done: Processed 0 articles, 0 drafts, 3 pages and 0 hidden pages in 0.16 seconds.
site runtests: commands[1] | python push-gh /home/mahmoud/projects/pyninsula_website/build/tox/site/tmp/output git@github.com:pyninsula/pyninsula.github.io.git
Initialized empty Git repository in /home/mahmoud/projects/pyninsula_website/build/tox/site/tmp/output/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'mahmoud@basalt.(none)')
Traceback (most recent call last):
  File "push-gh", line 23, in <module>
    main()
  File "push-gh", line 20, in main
    override_with(git, sys.argv[2], '--activate' in sys.argv)
  File "push-gh", line 13, in override_with
    git('commit', '-m', 'Initial commit', '--author', 'Pyninsula <admin@pyninsula.org>')
  File "push-gh", line 7, in _git
    subprocess.check_call(command, cwd=dname)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Initial commit', '--author', 'Pyninsula <admin@pyninsula.org>']' returned non-zero exit status 128
ERROR: InvocationError: '/home/mahmoud/projects/pyninsula_website/build/tox/site/bin/python push-gh /home/mahmoud/projects/pyninsula_website/build/tox/site/tmp/output git@github.com:pyninsula/pyninsula.github.io.git'
```
Even though I def have that set.

Also, I was right and editing/pushing the html was faster. But at least all the changes are ported in.

**Comment by mahmoud** [comment]
Haha, only 5 years later, I have a +1. The latest push highlighted:

1. Our pelican is still on Py2 (had to pin Pelican version to 4.2.0)
2. The tox push gh step breaks bc local git doesn't see my global git config username/password oddly. (The issue above)
3. The CloudFlare 2FA meta appears to be dropped (I caught it in the diff and readded manually before pushing to the github.io site)

We'll get around to it eventually!
